# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

# Core dependencies
gem 'optparse', '~> 0.4.0'

# For parsing various citation formats
gem 'bibtex-ruby', '~> 6.0'
gem 'citeproc-ruby', '~> 2.0'
gem 'csl-styles', '~> 2.0'

# For date parsing
gem 'chronic', '~> 0.10.2'

# Development dependencies
group :development do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
end

# Testing dependencies
group :test do
  gem 'simplecov', '~> 0.22'
end
